language: php

php:
  - 5.3
  - 5.4

before_script:
  - "sh -c 'curl -s http://getcomposer.org/installer | php'"
  - "sh -c 'php composer.phar install --dev --quiet'"

script: php tests/lint -R app && php tests/lint -R tests/cases && phpunit --configuration tests/phpunit.xml

notifications:
  email: false
